services:
  couchbase:
    container_name: couchbase
    image: couchbase
    ports:
      - '8091:8091'
      - '8092:8092'
      - '8093:8093'
      - '8094:8094'
      - '11210:11210'
version: '3.7'
